apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzd2VhdHkxMTExIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9ndmhPRVZJM3FjLTdFY0IyeVZxQ0FiM2E4RzAiLCJlbWFpbCI6ImFydGVtYnJpZ2F6QGdtYWlsLmNvbSIsImF1dGgiOiJjM2RsWVhSNU1URXhNVHBrWTJ0eVgzQmhkRjluZG1oUFJWWkpNM0ZqTFRkRlkwSXllVlp4UTBGaU0yRTRSekE9In19fQ==
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: python-app
type: kubernetes.io/dockerconfigjson




