apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/reflection21/devops-danit-final-project/kubernetes"
    targetRevision: main
    path: kubernetes/app
  destination:
    server: https://kubernetes.default.svc
    namespace: python-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
